/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CredentialUtils */

#ifndef _Included_CredentialUtils
#define _Included_CredentialUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CredentialUtils
 * Method:    getKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CredentialUtils_getKey
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
